### ISSUE TITLE
While using jtskit infer it returns unicode char with each key, value

### ISSUE THREAD

**Issue by jpatel3** [okfn/jtskit-py#9]
Is there any quick way to get regular string dict for the schema. Currently by default it returns the unicode key, value dict in return of - `jtskit.infer(header, data)`?

**Comment by pwalsh** [comment]
JTSKit uses unicode strings everywhere: this is a design decision in order to facilitate compatibility from Python 2.7 > 3.4 and above.

You must be using Python 2. Due to the way string handling works in Python 2, I can't think of any use case where returning unicode strings would be problematic.

Would you be able to explain a bit more/provide a use case describing the issue with JTSKit using unicode strings?

**Comment by jpatel3** [comment]
@pwalsh - I think you are right, It works fine and does as expected.

I was trying to use the schema generated for something else - generating jsont-table-schema from infer and saving it in db along side the uploaded CSVs and allowing user the capability to override the default type of the fields if required.

**Comment by pwalsh** [comment]
@jpatel3 ok good. If I can help with anything let me know. I'm closing this issue now but feel free to reopen, or start a new one, with any further problems.
